name: Deploy Static HTML to GitHub Pages

on:
  push:
    branches: ["main"]

  # Позволяет запускать деплой вручную из вкладки Actions
  workflow_dispatch:

# Разрешения для работы с GitHub Pages и токеном GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Разрешаем только один параллельный деплой
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Указываем путь к папке со статикой (root)
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
